[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

[dependencies]
panic-halt = "0.2.0"
k210-hal = { git="https://github.com/riscv-rust/k210-hal" }
riscv-rt = "0.8.1"
riscv = "0.8.0"
embedded-hal = "0.2.7"
